name: CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04-ppc64le
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          architecture: ppc64le
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Linter
        run: npm run eslint
      - name: Run Formatter
        run: npm run prettier

  test:
    name: Test - ${{ matrix.node-version }}
    runs-on: ubuntu-24.04-ppc64le
    strategy:
      fail-fast: false
      matrix:
        node-version: [latest, lts/*, lts/-1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ppc64le
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  api:
    name: API & Doc Validation
    runs-on: ubuntu-24.04-ppc64le
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          architecture: ppc64le
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Extract API
        run: npm run api:extract
      - name: Generate docs
        run: npm run api:docs
      - name: Ensure API and doc changes have been committed
        run: |
          git add --renormalize .
          if (( "$(git diff HEAD --ignore-space-at-eol --ignore-cr-at-eol | wc -l)" != 0 )); then
            cat << EOF >> $GITHUB_STEP_SUMMARY
          ### Detected uncommitted changes

          \`\`\`shell
          $(git diff HEAD)
          \`\`\`
          EOF
            git diff HEAD
            exit 1
          fi
