name: Integration

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

defaults:
  run:
    # Setting an explicit bash shell ensures GitHub Actions enables pipefail mode too,
    # rather than only error on exit (improving failure UX when pipes are used). See:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  integration-with-canvas:
    name: Integration (jsdom + node-canvas)
    runs-on: ubuntu-22.04-ppc64le
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./tough-cookie
      - uses: actions/checkout@v4
        with:
          repository: jsdom/jsdom
          ref: main
          path: ./jsdom
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          architecture: ppc64le
      - name: Install required image manipulation packages with APT
        run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev -y 
      - name: Build tough-cookie
        id: package
        run: |
          npm ci
          npm run build
          echo "tough_cookie_tarball=$(npm pack)" >> "$GITHUB_OUTPUT"
        working-directory: ./tough-cookie
      - name: Setup HOSTS file for Web Platform Test server
        run: ./test/web-platform-tests/tests/wpt make-hosts-file | sudo tee -a /etc/hosts
        working-directory: ./jsdom
      - name: Install jsdom dependencies
        run: |
          npm ci
          npm uninstall tough-cookie
          npm install ../tough-cookie/${{ steps.package.outputs.tough_cookie_tarball }}
          npm install canvas
        working-directory: ./jsdom
      - name: Run tests
        run: npm test -- --retries 1
        working-directory: ./jsdom
  integration:
    name: Integration (jsdom)
    runs-on: ubuntu-22.04-ppc64le
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./tough-cookie
      - uses: actions/checkout@v4
        with:
          repository: jsdom/jsdom
          ref: main
          path: ./jsdom
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          architecture: ppc64le
      - name: Build tough-cookie
        id: package
        run: |
          npm ci
          npm run build
          echo "tough_cookie_tarball=$(npm pack)" >> "$GITHUB_OUTPUT"
        working-directory: ./tough-cookie
      - name: Setup HOSTS file for Web Platform Test server
        run: ./test/web-platform-tests/tests/wpt make-hosts-file | sudo tee -a /etc/hosts
        working-directory: ./jsdom
      - name: Install jsdom dependencies
        run: |
          npm ci
          npm uninstall tough-cookie
          npm install ../tough-cookie/${{ steps.package.outputs.tough_cookie_tarball }}
        working-directory: ./jsdom
      - name: Run tests
        run: npm run test -- --retries 1
        working-directory: ./jsdom
